name: Artifact test
on: [push, pull_request]
jobs:
  artifact:
    # Job name is Greeting
    name: Upload artifact
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "please artifact me" > thefile.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test artifact
          path: thefile.txt
