name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
        
      - name: Create a dir and a file
        run: mkdir temp && cd temp && touch testfile
        
      - name: List dir contents with working-directory
        working-directory: ./temp
        run: ls
        
      - name: Clean temp directory
        run: rm -rf *
        working-directory: ./temp
      
      - name: After delete ls
        working-directory: ./temp
        run: ls
