name: Create issue on commit

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 10679_GITHUB_TOKEN_test
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - name: Create issue using REST API
      run: |
        curl --request POST --url https://api.github.com/repos/$GITHUB_REPOSITORY/issues --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{"title": "Automated issue for commit: TEST", "body": "This issue was automatically created by a GitHub Action. \n THe Commit hash was: TEST."}'
