name: Create issue on commit

on:
  push:
    branches:
      - 10679_GITHUB_TOKEN_test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      run: |
        curl --request POST --url https://api.github.com/repos/$GITHUB_REPOSITORY/issues --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json' --data '{"title": "Automated issue for commit: $GITHUB_SHA ", "body": "This issue was automatically created by the GitHub Action workflow * $GITHUB_WORKFLOW *. \n\n The Commit hash was: _ $GITHUB_SHA _."}'
