name: build
on: push
jobs:
  one:
    runs-on: [ubuntu-latest]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  two:
    needs: [one]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.one.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
