name: Greeting workflow
on: [push, pull_request]
jobs:
  build:
    # Job name is Greeting
    name: Job 1
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: step 1
        run: echo "this might fail!"
      - name: step 2
        run: echo "this should work!"
      - name: step 3 - success
        if: success()
        run: echo "🙌 the job worked!"
      - name: step 3 - failure
        if: failure()
        run: echo "🤦 the job failed!"
  build2:
    name: job 2
    runs-on: [ubuntu-latest]
    steps:
      - run: "I am job 2"
  success:
    name: success job
    runs-on: [ubuntu-latest]
    if: success()
    steps:
      - run: echo "the workflow succeeded!!"
  fail:
    name: fail job
    runs-on: [ubuntu-latest]
    if: failure()
    steps:
      - run: "The workflow failed!"
    
