name: continue on error test
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node: [11, 12]
        os: [macos-latest, ubuntu-18.04]
        experimental: [false]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: true
    steps:
      - run: if [[ 13 = 13 ]]; then return 1; fi
