name: Greeting workflow
on: [push, pull_request]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: |
          echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: external docker debug test # now contains a warning.
        uses: nohomers/no-homers-local-docker-action/.github/actions/local-hello-world@debug_log_test
