name: Test workflow
on: [push, pull_request]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.GITHUB_ACTOR }}
