name: New include
on: [push, pull_request]
jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12]
        os: [macos-latest, windows-latest, ubuntu-18.04]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: true
    steps:
      - run: echo hi!

  
