name: Greeting workflow
on: [push, pull_request]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: step 1
        run: echo "this might fail!" && exit 1
      - name: step 2
        run: echo "this should work!"
      - name: step 3 - success
        if: success()
        run: echo "🙌 the job worked!"
      - name: step 3 - failure
        if: failure()
        run: echo "🤦 the job failed!"
