name: continue on error test
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error }}
    strategy:
      fail-fast: false
      matrix:
        node: [11, 12]
        os: [macos-latest, windows-latest, ubuntu-18.04]
        include:
          - node: 13
            os: ubuntu-18.04
            continue-on-error: true
    steps:
      - run: if [[ ${{ matrix.node }} = 13 ]]; then return 1; fi
