name: build
on: push
jobs:
  job1:
    runs-on: [ubuntu-latest]
    # Map step output to job output
    outputs:
      test: ${{ steps.step1.outputs.hello }}
    steps:
      - id: step1
        run: echo "::set-output name=hello::hello_world"
  job2:
    runs-on: [ubuntu-latest]
    needs: job1
    steps:
      ## Print out hello_world
      - run: |
          echo ${{ needs.job1.outputs.test }}
