name: Test workflow
on: [push, pull_request]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: octocat 
    steps:
      - run: echo "Envs are usually a manually-defined environment variable: ${{ env.GITHUB_ACTOR }}"
      - run: echo "This is an automatic GitHub Actions-provided context: ${{ github.actor }}"
