name: Greeting workflow
on: [push, pull_request]
env:
  str: 'ABC'
  num: 123  
jobs:
  conditional:
    runs-on: ubuntu-latest
    steps:
    - run: echo "This step runs with str equals 'ABC' and num equals 123"
      if: env.str == 'ABC' && env.num == 123
