name: Greeting workflow
on: [push, pull_request]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Join test
        run: echo ${{ join(github.event.commits.*.*.username) }}
      - name: Contains test string
        run: echo ${{ contains('Hello world', 'llo') }}
      - name: Contains test array
        run: echo ${{ contains(github.event.commits.*.*.username, 'lucascosti') }}
      - name: Contains test array2
        run: echo ${{ contains(github.event.commits.*.*.username, 'frostysonic') }}
          
